<script type="text/javascript">
function validateForm(){
	if( $('#user_id').val()=='' || $('#title').val()=='' || $('#description').val()=='' || 
			$('#approved').val()=='' || $('#image').val()=='' || $('#ranking').val()=='' ){
		alert('Complete todos los campos');
		return false;
	}else
		return true;
}
</script>	
	
<?= $this->getAdminLayout('Posts') ?>
<h3 class="tit">Crear Post</h3> 					
			<p class="msg info">Por favor, llene todos los campos obligatorios</p>
			<p class="msg info">Si agrega WEB asgurese de poner http:// para que la redireccion funcione correctamente</p>
			<p class="msg info">El usuario debe ser creado anteriormente</p>
			<p class="msg info">La puntuaci&oacute;n sirve para dar mayor o menor revelacia a los posts que se muestran en la web</p>
			<p class="msg info">en la web mostramos los post en orden descendiente tomando como referencia la puntuaci&oacute;n y fecha de modificaci&oacute;n</p>			
		    <fieldset>
		    <legend>Crear Post</legend>
		     <form id="houseform"  action="<?=$this->baseUrl()?>/backend/add-post?add=true" method="post" onsubmit="return validateForm();" enctype="multipart/form-data" >		     			
					<table class="nostyle">																									
						<tr>
							<td>Usuario:</td>
							<td>
								<select name="user_id" id="user_id">
									<option></option>
								<?php 
								foreach ($this->users as $user){
								?>
									<option value="<?=$user['id']?>"><?=$user['name']?> - <?=$user['email']?></option>
								<?php	
								}
								?>
								</select>								
							</td>
						</tr>
						<tr>
							<td>T&iacute;tulo:</td>
							<td><input type="text" name="title" id="title" class="input-text"></input></td>
						</tr>
						<tr>
							<td>Descrtipci&oacute;n:</td>
							<td><textarea name="description" id="description" class="input-text" rows="3" cols="38"></textarea></td>
						</tr>
						<tr>
							<td>Web:</td>
							<td><input type="text" name="web" id="web" class="input-text"></td>
						</tr>
						<tr>
						  	<td class="va-top">Aprobaci&oacute;n:</td>
						  	<td>
					          	<select name="approved" id="approved" >  								
	  								<option value="0">Denegada</option>
	  								<option value="1">Aprobada</option>  	  								
								</select> 					          	
					      	</td>
						</tr>
						<tr>
							<td>Puntuaci&oacute;n:</td>
							<td>
								<select name="ranking" id="ranking" >  								
	  								<option value="1">1</option>
	  								<option value="2">2</option>  
	  								<option value="3">3</option>
	  								<option value="4">4</option>
	  								<option value="5">5</option>
								</select>
							</td>
						</tr>	                    	        	                    						
                    	<tr>
						  	<td class="va-top">Imagen:</td>
						  	<td>
					          	<span id="input_imagen">                        
					             	<input name="image" id="image" type="file" />
					          	</span> 					          	
					      	</td>
						</tr>	                    							                      					
						<tr>
							<td colspan="2" class="t-right"><input type="submit" class="input-submit" value="Crear" /></td>
						</tr>
					</table>
			</form>
		    </fieldset>
<?= $this->getAdminFooter() ?>				