<script type="text/javascript">
function check_empty(){
	var result = true;
	$('input:text').each(function() {
	   if( $(this).val()=='' ){ 			   
			$(this).addClass('error');
			$(".errorMessage").show();										 		   
	        result = false;
	   }else{
		   $(this).removeClass("error");
	   }	   		        		   
	});
	if(result==false){
		alert('Complete todos los campos');
	}
	return result;				
}
</script>	
	
<?= $this->getAdminLayout('Casas') ?>
<h3 class="tit">Crear Casa</h3> 					
			<p class="msg info" id="errorMessage">Por favor, llene todos los campos obligatorios</p>
			<?php 
				if ($_GET['status']=='fail') 
					echo '<p class="msg error">Error</p>';			 	
			?>							
		    <fieldset>
		    <legend>Crear Casa</legend>
		     <form id="houseform"  action="<?=$this->baseUrl()?>/backend/add-house?add=true" method="post" onsubmit="return check_empty();" enctype="multipart/form-data" >		     			
					<table class="nostyle">																									
						<tr>
							<td>Nombre:</td>
							<td><input placeholder="Nombre de casa..." type="text" size="40" name="name" id="name" class="input-text" value="<?= $this->house['name']; ?>" /></td>
						</tr>
						<tr>
							<td>Cantidad de personas:</td>
							<td>
								<select name="type" id="type">  								
	  								<option value="">- elija -</option>
	  								<option value="4">4</option>  
	  								<option value="6">6</option>
								</select>
							</td>
						</tr>	                    
	                    <tr>
							<td>Precio Temporada Alta:</td>
							<td><input placeholder="Ingrese precio..." type="text" size="40" name="high_price" class="input-text" id="high_price" value="<?= $this->house['high_price']; ?>" /></td>
						</tr>
	                    <tr>
							<td>Precio Temporada Media:</td>
							<td><input placeholder="Ingrese precio..." type="text" size="40" name="medium_price" id="medium_price" class="input-text"  value="<?= $this->house['medium_price']; ?>" /></td>
						</tr>
	                    <tr>
							<td>Precio Temporada Baja:</td>
							<td><input placeholder="Ingrese precio..." type="text" size="40" name="low_price" id="low_price" class="input-text"  value="<?= $this->house['low_price']; ?>" /></td>
						</tr>
						<tr>
							<td>Precio Especial:</td>
							<td><input placeholder="Ingrese precio..." type="text" size="40" name="special_price" id="special_price" class="input-text"  value="<?= $this->house['special_price']; ?>" /></td>
						</tr>
						<tr>
							<td>Precio Carnaval:</td>
							<td><input placeholder="Ingrese precio..." type="text" size="40" name="carnival_price" id="carnival_price" class="input-text"  value="<?= $this->house['carnival_price']; ?>" /></td>
						</tr>
						<tr>
							<td>Detalles - Tareas - Notas:</td>
							<td><textarea  name="description" id="description" class="input-text" rows="3" cols="38"> <?= $this->house['description']; ?></textarea></td>
						</tr>	                      						
						<tr>
							<td colspan="2" class="t-right"><input type="submit" class="input-submit" value="Crear" /></td>
						</tr>
					</table>
			</form>
		    </fieldset>
<?= $this->getAdminFooter() ?>				