<?php echo $this->doctype();?>
<html>
<head>
	
	<title>Administraci&oacute;n Casas de la Playa - Calendario</title>	
    <?php
    	echo $this->headMeta();
    ?>
    <meta name="robots" content="noindex,nofollow" />		
    <script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js"						type="text/javascript"></script>     		
	<script src="<?=$this->baseUrl()?>/js/newweb_js/ui/js/jquery-ui-1.9.2.custom.min.js" 		type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/bootstrap.min.js" 							type="text/javascript"></script>
	
	<script type="text/javascript" src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/language/es-ES.js"></script>    
    <script type="text/javascript" src="<?=$this->baseUrl()?>/js/bootstrap_calendar/components/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/calendar.js"></script>
	<link href="<?=$this->baseUrl()?>/js/bootstrap_calendar/css/calendar.css" 	rel="stylesheet">
	
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap.min.css" 		rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap-responsive.css" 	rel="stylesheet" type="text/css"/>		
	<link href="<?=$this->baseUrl()?>/images/favicon.gif" 						rel="shortcut icon"/>
	<link href="<?=$this->baseUrl()?>/images/favicon.ico" 						rel="shortcut icon"/>           
    
</head>

<script type="text/javascript">
	var calendar = $('#calendar').calendar({
						language: 'es-ES',
						events_source: [
				                 {
				                     "id": 293,
				                     "title": "Event 1",
				                     "url": "http://example.com",
				                     "class": 'event-important',
				                     "start": 1389686400000, // Milliseconds
				                     "end": 1389859200000 // Milliseconds
				                 },
				                 {
				                     "id": 294,
				                     "title": "Event 2",
				                     "url": "http://example.com",
				                     "class": 'event-important',
				                     "start": 1389859200000, // Milliseconds
				                     "end": 1392537600000 // Milliseconds
				                 }				                 						     
						]
						
					});
</script>
	
<body>

    <div id="calendar"></div>
    <?php 
         
    //echo $this->price;
    echo $this->events;
    ?>
    
</body>
</html>