<?php echo $this->doctype();?>
<html>
<head>
	
	<title>Administraci&oacute;n Casas de la Playa - Calendario</title>	
    <?php
    	echo $this->headMeta();
    ?>
    <meta name="robots" content="noindex,nofollow" />		   
	<link href="<?=$this->baseUrl()?>/js/bootstrap_calendar/css/calendar.css" 	rel="stylesheet">	
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap.min.css" 		rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap-responsive.css" 	rel="stylesheet" type="text/css"/>		
	<link href="<?=$this->baseUrl()?>/images/favicon.gif" 						rel="shortcut icon"/>
	<link href="<?=$this->baseUrl()?>/images/favicon.ico" 						rel="shortcut icon"/>           
    
</head>
	
<body>
<form>
	<div class="container">
		<div class="hero-unit" style="padding: 22px; important!">
			<h2>Calendario Casas de la Playa</h2>	
			<a class="btn btn-inverse" href="http://casasdelaplayadelapedrera.com/backend/user-list">Volver al Adminstrador</a>			
			<a href="http://casasdelaplayadelapedrera.com" class="btn btn-twitter" data-show-count="false" data-size="large">Volver al Sitio</a>						
		</div>
		
		<div class="page-header" style="padding-bottom: 36px; important!">
			<div class="pull-right form-inline">
				<div class="btn-group">
					<button class="btn btn-primary" data-calendar-nav="prev"><< Anterior</button>
					<button class="btn" data-calendar-nav="today">Hoy</button>
					<button class="btn btn-primary" data-calendar-nav="next">Siguiente >></button>
				</div>
				<div class="btn-group">
					<button class="btn btn-warning" data-calendar-view="year">A&ntilde;o</button>
					<button class="btn btn-warning active" data-calendar-view="month">Mes</button>
					<button class="btn btn-warning" data-calendar-view="week">Semana</button>
					<button class="btn btn-warning" data-calendar-view="day">D&iacute;a</button>
				</div>
			</div>
			<h3></h3>			
		</div>

	    <div id="calendar"></div>
	    
		<script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js"						type="text/javascript"></script>     		    
		<script src="<?=$this->baseUrl()?>/js/newweb_js/ui/js/jquery-ui-1.9.2.custom.min.js" 		type="text/javascript"></script>
		<script src="<?=$this->baseUrl()?>/js/newweb_js/bootstrap.min.js" 							type="text/javascript"></script>	
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/language/es-ES.js"  			type="text/javascript"></script>    
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/components/underscore/underscore-min.js" type="text/javascript"></script>
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/calendar.js"					type="text/javascript"></script>
		<script type="text/javascript">
			
		(function($) {

			"use strict";

			var options = {
				language: 'es-ES',
				events_source: <?=$this->events?>,
				first_day: 1,		
				view: 'month',				
				tmpl_cache: false,
				//day: '2013-03-12',
				onAfterEventsLoad: function(events) {
					if(!events) {
						return;
					}
					var list = $('#eventlist');
					list.html('');
					$.each(events, function(key, val) {
						$(document.createElement('li'))
							.html('<a href="' + val.url + '">' + val.title + '</a>')
							.appendTo(list);
					});
				},
				onAfterViewLoad: function(view) {
					$('.page-header h3').text(this.getTitle());
					$('.btn-group button').removeClass('active');
					$('button[data-calendar-view="' + view + '"]').addClass('active');
				},
				classes: {
					months: {
						general: 'label'
					}
				}
			};

			var calendar = $('#calendar').calendar(options);

			$('.btn-group button[data-calendar-nav]').each(function() {
				var $this = $(this);
				$this.click(function() {
					calendar.navigate($this.data('calendar-nav'));
				});
			});

			$('.btn-group button[data-calendar-view]').each(function() {
				var $this = $(this);
				$this.click(function() {
					calendar.view($this.data('calendar-view'));
				});
			});				

			$('#events-in-modal').change(function(){
				//var val = $(this).is(':checked') ? $(this).val() : null;
				var val =  $(this).val();
				calendar.setOptions({modal: val});
			});
			$('#events-modal .modal-header, #events-modal .modal-footer').click(function(e){
				e.preventDefault();
				e.stopPropagation();
			});
		}(jQuery));					
																
		</script>
            
	</div>
</form>	
</body>
</html>