<?php echo $this->doctype();?>
<html>
<head>
	
	<title>Administraci&oacute;n Casas de la Playa - Calendario</title>	
    <?php
    	echo $this->headMeta();
    ?>
    <meta name="robots" content="noindex,nofollow" />		   
	<link href="<?=$this->baseUrl()?>/js/bootstrap_calendar/css/calendar.css" 	rel="stylesheet">	
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap.min.css" 		rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap-responsive.css" 	rel="stylesheet" type="text/css"/>		
	<link href="<?=$this->baseUrl()?>/images/favicon.gif" 						rel="shortcut icon"/>
	<link href="<?=$this->baseUrl()?>/images/favicon.ico" 						rel="shortcut icon"/>           
    
</head>
	
<body>
<form>
	<div class="container">
		<div class="hero-unit" style="padding: 22px; important!">
			<h2>Calendario Casas de la Playa</h2>	
			<a class="btn btn-inverse" href="http://casasdelaplayadelapedrera.com/backend/user-list">Volver al Adminstrador</a>			
			<a href="http://casasdelaplayadelapedrera.com" class="btn btn-twitter" data-show-count="false" data-size="large">Volver al Sitio</a>						
		</div>
		
		<div class="page-header" style="padding-bottom: 36px; important!">
			<div class="pull-right form-inline">
				<div class="btn-group">
					<button class="btn btn-primary" data-calendar-nav="prev"><< Prev</button>
					<button class="btn" data-calendar-nav="today">Today</button>
					<button class="btn btn-primary" data-calendar-nav="next">Next >></button>
				</div>
				<div class="btn-group">
					<button class="btn btn-warning" data-calendar-view="year">Year</button>
					<button class="btn btn-warning active" data-calendar-view="month">Month</button>
					<button class="btn btn-warning" data-calendar-view="week">Week</button>
					<button class="btn btn-warning" data-calendar-view="day">Day</button>
				</div>
			</div>
			<h3></h3>			
		</div>

	    <div id="calendar"></div>
	    
		<script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js"						type="text/javascript"></script>     		    
		<script src="<?=$this->baseUrl()?>/js/newweb_js/ui/js/jquery-ui-1.9.2.custom.min.js" 		type="text/javascript"></script>
		<script src="<?=$this->baseUrl()?>/js/newweb_js/bootstrap.min.js" 							type="text/javascript"></script>	
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/language/es-ES.js"  			type="text/javascript"></script>    
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/components/underscore/underscore-min.js" type="text/javascript"></script>
		<script src="<?=$this->baseUrl()?>/js/bootstrap_calendar/js/calendar.js"					type="text/javascript"></script>
		<script type="text/javascript">
			/** var calendar = $('#calendar').calendar({
								language: 'es-ES',
								events_source: [						               
						                 {
						                     "id": 294,
						                     "title": "Event 2",
						                     "url": "http://example.com",
						                     "class": 'event-important',
						                     "start": 1389859200000, // Milliseconds
						                     "end": 1392537600000 // Milliseconds
						                 }				                 						     
								]								
							});**/
							
				var calendar = $('#calendar').calendar({
					language: 'es-ES',
					events_source: <?=$this->events?>,
					 onAfterEventsLoad: function(events) {
						 $.each(events, function() {
							 console.info(this);
					         this['class'] = "event-warning";
					         //delete this['myClass'];
					      });  
					   }						 													
				});					
		</script>
            
	</div>
</form>	
</body>
</html>