<link rel="stylesheet" media="screen" type="text/css" href="<?=$this->baseUrl()?>/js/colorpicker/css/colorpicker.css" />
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/colorpicker/js/colorpicker.js"></script>

<script type="text/javascript">
function validateForm(){
	if( $('#start_date').val()=='' || $('#end_date').val()=='' || $('#color').val()=='' ){
		alert('Complete todos los campos');
		return false;
	}else	
		return confirm('Realmente quieres editar la temporada?');	
}
$(document).ready(function(){		
	$( "#start_date" ).datepicker({
			minDate: -999*99,
			changeMonth: true,
			changeYear: true,								
			yearRange: "2013:2016"
	});
	$( "#end_date" ).datepicker({
		minDate: -999*99,
		changeMonth: true,
		changeYear: true,								
		yearRange: "2013:2016"
	});	
	$('#color').ColorPicker({		
		onShow: function (colpkr) {
			$(colpkr).fadeIn(500);
			return false;			
		},
		onHide: function (colpkr) {
			$(colpkr).fadeOut(500);
			return false;			
		},		
		onSubmit: function(hsb, hex, rgb, el) {
			$(el).val(hex);
			$(el).ColorPickerHide();
			$('#color').attr('style','background-color:#'+hex);			
		},
		onBeforeShow: function () {
			$(this).ColorPickerSetColor(this.value);			
		}
	})
	.bind('keyup', function(){
		$(this).ColorPickerSetColor(this.value);		
	});	
});

</script>	
	
<?= $this->getAdminLayout('Season') ?>
<h3 class="tit">Editar <?= $this->season['rate_type']?> season</h3> 					
			<p class="msg info">Cuidado, estas a punto de editar una Temporada</p>
			<p class="msg info">Por favor, llene todos los campos obligatorios</p>				
		    <fieldset>
		    <legend>Editar Temporada</legend>
		     <form id="seasonform"  action="<?=$this->baseUrl()?>/backend/edit-season?id=<?=$this->season['id']?>&edit=true" method="post" onsubmit="return validateForm();" enctype="multipart/form-data" >		     			
					<table class="nostyle">																									
						<tr>
							<td>Fecha comienzo*:</td>
							<td><input type="text" size="40" name="start_date" id="start_date" class="input-text" value="<?= $this->season['start_date']; ?>" /></td>
						</tr>
						<tr>
							<td>Fecha fin*:</td>
							<td><input type="text" size="40" name="end_date" id="end_date" class="input-text" value="<?= $this->season['end_date']; ?>" /></td>
						</tr>	                    
	                    <tr>
							<td>Color*:</td>
							<td><input type="text" size="6" name="color" id="color" class="input-text"  style="background-color: #<?=$this->season['color']?>" value="<?= $this->season['color']; ?>" /></td>																						
						</tr>												                    						
						<tr>
							<td colspan="2" class="t-right"><input type="submit" class="input-submit" value="Guardar Cambios" /></td>
						</tr>
					</table>							
			</form>
		    </fieldset>
<?= $this->getAdminFooter() ?>				