<script language="Javascript">
	function decision(message, url){
		if(confirm(message)) 
			location.href = url;
	}
</script> 

	<?= $this->getAdminLayout('Casas') ?>	   
	<?php if ($this->msg != ''){ ?>
		<p class="msg done"><?=$this->msg; ?></p>
	<?php } ?>
      <h3 class="tit">Listado de Casas</h3>                    
      <table>
            <tbody>
            <tr>
              <th>Nombre</th>
              <th>Precio Temp Baja</th>
              <th>Precio Temp Media</th>
              <th>Precio Temp Alta</th>
              <th>Precio Especial</th>
              <th>Acci&oacute;n</th>
            </tr>            
          <?php 
          $i = 0;
          foreach ($this->habitaciones as $habitacion){
          	$i++; ?>  
           <tr <?php if ($i%2==0){ ?> class="bg" <?php } ?> >
              <td><a href="<?=$this->baseUrl();?>/backend/view-house?id=<?=$habitacion['id'];?>"><b><?=$habitacion['name'];?></b></a></td>
              <td>$ <?=$habitacion['low_price'];?></td>              
              <td>$ <?=$habitacion['medium_price'];?></td>
              <td>$ <?=$habitacion['high_price'];?></td>
              <td>$ <?=$habitacion['special_price'];?></td>              
              <td align="center">
              		<a href="<?=$this->baseUrl();?>/backend/view-house?id=<?=$habitacion['id'];?>">
             			<img src="<?=$this->baseUrl()?>/img/icons2/house.png" title="Ver Detalles" width="16" height="16" alt="del">
             		</a>
              		<a href="<?=$this->baseUrl()?>/backend/edit-house?id=<?=$habitacion['id'];?>">
              			<img src="<?=$this->baseUrl()?>/img/icons2/edit.png" title="Editar" width="16" height="16" alt="edit">
              		</a>
             		<a href="javascript:decision('¿Está seguro que desea borrar esta Casa? El borrado incorrecto puede causar inestabilidad en el sistema','<?=$this->baseUrl()?>/backend/delete-house?id=<?=$habitacion['id'];?>')">
             			<img src="<?=$this->baseUrl()?>/img/icons2/trash_closed.png" title="Eliminar" width="16" height="16" alt="del">
             		</a>
             	</td>            
            </tr>
            <?php } ?>
            </tbody></table>
      <br>
      <p>&nbsp;</p>
      
      <?= $this->getAdminFooter() ?>