<?= $this->getAdminLayout('none') ?>
	<h1>Administrador Casas de la Playa</h1>
	<!-- Headings -->
	<!--	<p class="msg warning">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	<p class="msg info">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	<p class="msg done">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	<p class="msg error">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>-->
	<p class="msg info">Bienvenido al administrador </p>			
	<p class="msg info">Usted podr&aacute; hacer altas, bajas, listados y modificaciones de Casas, Mensajes, Posts, Reservas, Temporadas y Usuarios</p>                              
<?= $this->getAdminFooter() ?>

	