<script language="Javascript">
	function decision(season, url){
		if(confirm(season)) 
			location.href = url;
	}
</script> 
<style>
.pm{
	border-style: solid;
	border-width: 0 0;
	width: 11px;
	height: 11px;
	position: relative;
	left:43%;	  	  	
}
</style>

	<?= $this->getAdminLayout('Temporadas') ?>	   
	<?php if ($this->msg != ''){ ?>
		<p class="msg done"><?=$this->msg; ?></p>
	<?php } ?>
      <h3 class="tit">Listado de Temporadas</h3>                    
      <table>
            <tbody>
            <tr>
              <th>Tipo tarifa</th>              
              <th>Desde</th>
              <th>Hasta</th>
              <th>Fecha modificaci&oacute;n</th>
              <th>Color</th>
              <th>Editar</th>
            </tr>            
          <?php 
          $i = 0;
          foreach ($this->seasons as $season){
          	$i++; ?>  
           <tr <?php if ($i%2==0){ ?> class="bg" <?php } ?> >           		                            
              <td><?=$season['rate_type'];?></td>
              <?php               
              		require_once('../library/utils/fecha.class.php');
            		$fecha_obj = new Fecha();
            		$fecha_obj->setFecha($season['start_date'])
           	  ?>
              <td><?=$fecha_obj->getFecha()->format('d/m/Y');?></td>
              <?php                             		
            		$fecha_obj = new Fecha();
            		$fecha_obj->setFecha($season['end_date'])
           	  ?>
              <td><?=$fecha_obj->getFecha()->format('d/m/Y');?></td>                                                        
              <td><?=$season['date_modified'];?></td>              
              <td>
              	<div class="pm" style="background-color: #<?=$season['color']?>"></div>             
              </td>
              <td align="center">              		              		
             		<a href="<?=$this->baseUrl()?>/backend/edit-season?id=<?=$season['id'];?>">
             			<img src="<?=$this->baseUrl()?>/img/icons2/edit.png" title="Editar" width="16" height="16" alt="edit">
             		</a>
             	</td>            
            </tr>
            <?php } ?>
            </tbody></table>
      <br>
      <p>&nbsp;</p>
      
      <?= $this->getAdminFooter() ?>