 <?= $this->getAdminLayout('Usuarios') ?>	   
      <h3 class="tit">Listado de Usuarios</h3>
      
      <div class="pagLetras"> 
      	<a href="<?=$this->baseUrl()?>/backend/user-list?letter=A">A</a>
        <a href="<?=$this->baseUrl()?>/backend/user-list?letter=B">B</a>
        <a href="<?=$this->baseUrl()?>/backend/user-list?letter=C">C</a>
        <a href="<?=$this->baseUrl()?>/backend/user-list?letter=D">D</a>
        <a href="<?=$this->baseUrl()?>/backend/user-list?letter=E">E</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=F" >F</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=G" >G</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=H" >H</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=I" >I</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=J" >J</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=K" >K</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=L" >L</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=M" >M</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=N" >N</a>                  
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=O" >O</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=P" >P</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=Q" >Q</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=R" >R</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=S" >S</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=T" >T</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=U" >U</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=V" >V</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=W" >W</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=X" >X</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=Y" >Y</a>
                  <a href="<?=$this->baseUrl()?>/backend/user-list?letter=Z" >Z</a>
                  <br/><br/>
                  <a href="<?=$this->baseUrl()?>/backend/user-list" >Ver Todos</a>
                  <br/><br/>
              </div>
      
      <?php
	if ($_GET['edited']=='ok') { 
		echo '<p class="msg done">Se ha editado la Usuario con &eacute;xito!</p>'; 
 	}else if ($_GET['status']=='fail') { 
		echo '<p class="msg error">Error</p>';
 	}else if ($_GET['added']=='ok') { 
		echo '<p class="msg done">Se ha agregado un nuevo Usuario con &eacute;xito!</p>';
 	}else if ($_GET['deleted']=='ok') { 
		echo '<p class="msg done">Se ha eliminado al Usuario con &eacute;xito!</p>';
 	}
?>		                     
      <table>
            <tbody>
            <tr>
              <th>Nombre</th>
              <th>Email</th>
              <th>Telefono</th>
              <th>Pais</th>
              <th>Ciudad</th>
              <th>Fecha nacimiento</th>
              <th>Identificador civil</th>
              <th>Fecha creacion</th>              
              <th>Acciones</th>
            </tr>            
          <?php 
          $i = 0;
          foreach ($this->users as $user){
          	$i++; ?>  
           <tr <?php if ($i%2==0){ ?> class="bg" <?php } ?> >
              <td><a href="<?=$this->baseUrl();?>/backend/view-user?id=<?=$user['id'];?>"><b><?=$user['name'];?></b></a></td>                           
              <td><?=$user['email'];?></td>
              <td><?=$user['phone'];?></td>
              <td><?=$user['country'];?></td>
              <td><?=$user['city'];?></td>
              <td><?=$user['date_birth'];?></td>
              <td><?=$user['civil_identifier'];?></td>                          
              <td><?=$user['date_created'];?></td>
              <td align="center">              		              		
             		<a href="<?=$this->baseUrl();?>/backend/view-user?id=<?=$user['id'];?>">
             			<img src="<?=$this->baseUrl()?>/img/icons2/house.png" title="Ver Detalles" width="16" height="16" alt="del">
             		</a>
              		<a href="<?=$this->baseUrl()?>/backend/edit-user?id=<?=$user['id'];?>">
              			<img src="<?=$this->baseUrl()?>/img/icons2/edit.png" title="Editar" width="16" height="16" alt="edit">
              		</a>
             		<a href="javascript:decision('¿Está seguro que desea borrar este Usuario? El borrado incorrecto puede causar inestabilidad en el sistema','<?=$this->baseUrl()?>/backend/delete-user?id=<?=$user['id'];?>')">
             			<img src="<?=$this->baseUrl()?>/img/icons2/trash_closed.png" title="Eliminar" width="16" height="16" alt="del">
             		</a>
             	</td>            
            </tr>
            <?php } ?>
            </tbody></table>
      <br>
      <p>&nbsp;</p>
      
      <?= $this->getAdminFooter() ?>