	<div id="cont_left">
        <h1>Alojamientos</h1>
        <p>Casas de la Playa ofrece una excelente alternativa de alojamiento en cuanto a ubicaci&oacute;n, equipamiento, servicios y confort.  Contamos con servicio de mucama diario, ropa blaca, wi-fi, tv cable plasma, aire acondicionado, cocina completa, barbacoa, espacios exteriores, cochera, terrazas en 2 niveles con los pies en la arena frente a la zona de ba&ntilde;o.</p>
        <a href="<?=$this->baseUrl()?>/index/galeria">Click para ver Fotos</a>
        <p>Cada unidad es para 4 personas.Cuentan con un dormitorio matrimonial con terraza y una vista al mar inmejorableen el nivel superior. Independiente del dormitorio, en planta alta, se encuentra el ba&ntilde;o y un vestidor. En planta baja se encuentra el living cocina con terraza hacia el mar y un deck en el fondo.</p>
        <a href="<?=$this->baseUrl()?>/index/servicios" id="btn_ficha">Ver ficha de equipamiento</a>
    </div>
    <div id="cont_right">
    	<img src="<?=$this->baseUrl()?>/img/deco/img_alojamientos.jpg" width="589" height="529" />
	</div>