<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jquery.history.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jquery.galleriffic.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jquery.opacityrollover.js"></script>
<link 	href="<?=$this->baseUrl()?>/css/oldweb_css/galleriffic-4.css" rel="stylesheet" type="text/css" />
<!-- We only want the thunbnails to display when javascript is disabled -->
<script type="text/javascript">
	document.write('<style>.noscript { display: none; }</style>');
	
	 if (navigator.appName.indexOf("Explorer") != -1) { 
		alert('Usted esta usando Internet Explorer, no podra usar la galeria de imagenes. Por favor utilize cualquier otro navegador para visualizar la misma'); 
	} 		
</script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		// We only want these styles applied when javascript is enabled
		$('div.navigation').css({'width' : '270px', 'float' : 'left'});
		$('div.content').css('display', 'block');

		// Initially set opacity on thumbs and add
		// additional styling for hover effect on thumbs
		var onMouseOutOpacity = 0.67;
		$('#thumbs ul.thumbs li').opacityrollover({
			mouseOutOpacity:   onMouseOutOpacity,
			mouseOverOpacity:  1.0,
			fadeSpeed:         'fast',
			exemptionSelector: '.selected'
		});

		// Enable toggling of the caption
		var captionOpacity = 0.0;
		$('#captionToggle a').click(function(e) {
			var link = $(this);
			
			var isOff = link.hasClass('off');
			var removeClass = isOff ? 'off' : 'on';
			var addClass = isOff ? 'on' : 'off';
			var linkText = isOff ? 'Hide Caption' : 'Show Caption';
			captionOpacity = isOff ? 0.7 : 0.0;

			link.removeClass(removeClass).addClass(addClass).text(linkText).attr('title', linkText);
			$('#caption span.image-caption').fadeTo(1000, captionOpacity);
			
			e.preventDefault();
		});
		
		// Initialize Advanced Galleriffic Gallery
		var gallery = $('#thumbs').galleriffic({
			delay:                     2500,
			numThumbs:                 12,
			enableTopPager:            false,
			enableBottomPager:         true,
			maxPagesToShow:            7,
			imageContainerSel:         '#slideshow',
			captionContainerSel:       '#caption',
			loadingContainerSel:       '#loading',
			enableHistory:             true,
			autoStart:                 false,
			syncTransitions:           true,
			defaultTransitionDuration: 900,
			onSlideChange:             function(prevIndex, nextIndex) {
				// 'this' refers to the gallery, which is an extension of $('#thumbs')
				this.find('ul.thumbs').children()
					.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
					.eq(nextIndex).fadeTo('fast', 1.0);
			},
			onTransitionOut:           function(slide, caption, isSync, callback) {
				slide.fadeTo(this.getDefaultTransitionDuration(isSync), 0.0, callback);
				caption.fadeTo(this.getDefaultTransitionDuration(isSync), 0.0);
			},
			onTransitionIn:            function(slide, caption, isSync) {
				var duration = this.getDefaultTransitionDuration(isSync);
				slide.fadeTo(duration, 1.0);
				
				// Position the caption at the bottom of the image and set its opacity
				var slideImage = slide.find('img');
				caption.width(slideImage.width())
					.css({
						'bottom' : Math.floor((slide.height() - slideImage.outerHeight()) / 2),
						'left' : Math.floor((slide.width() - slideImage.width()) / 2) + slideImage.outerWidth() - slideImage.width()
					})
					.fadeTo(duration, captionOpacity);
			},
			onPageTransitionOut:       function(callback) {
				this.fadeTo('fast', 0.0, callback);
			},
			onPageTransitionIn:        function() {
				this.fadeTo('fast', 1.0);
			},
			onImageAdded:              function(imageData, $li) {
				$li.opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
			}
		});

		/**** Functions to support integration of galleriffic with the jquery.history plugin ****/

		// PageLoad function
		// This function is called when:
		// 1. after calling $.historyInit();
		// 2. after calling $.historyLoad();
		// 3. after pushing "Go Back" button of a browser
		function pageload(hash) {
			// alert("pageload: " + hash);
			// hash doesn't contain the first # character.
			if(hash) {
				$.galleriffic.gotoImage(hash);
			} else {
				gallery.gotoIndex(0);
			}
		}

		// Initialize history plugin.
		// The callback is called at once by present location.hash. 
		$.historyInit(pageload, "advanced.html");

		// set onlick event for buttons using the jQuery 1.3 live method
		$("a[rel='history']").live('click', function() {
			if (e.button != 0) return true;

			var hash = this.href;
			hash = hash.replace(/^.*#/, '');

			// moves to a new page. 
			// pageload is called at once. 
			// hash don't contain "#", "?"
			$.historyLoad(hash);

			return false;
		});

		/****************************************************************************************/

		/********************** Attach click event to the Add Image Link ************************/

		$('#addImageLink').click(function(e) {
			gallery.insertImage('<li>																							\
					<a class="thumb" href="images/galeria/thumbnails/1ch.jpg" title="Dynamically Added Image">\
						<img src="images/galeria/1g.jpg" alt="Dynamically Added Image" />\
					</a>																										\
					<div class="caption">																						\
						<div class="download">																					\
							<a href="http://farm1.static.flickr.com/79/263120676_2518b40e5b_o_d.jpg">Download Original</a>		\
						</div>																									\
						<div class="image-title">Dynamically Added Image</div>													\
						<div class="image-desc">																				\
							<img src="http://farm1.static.flickr.com/38/buddyicons/77261001@N00.jpg" alt="ringydingydo" />		\
							Photo taken by <a href="http://www.flickr.com/photos/ringydingydo/">ringydingydo</a>				\
						</div>																									\
					</div>																										\
				</li>', 5);
			
			e.preventDefault();
		});
		
		/****************************************************************************************/
		
		/***************** Attach click event to the Remove Image By Index Link *****************/
		
		$('#removeImageByIndexLink').click(function(e) {
			if (!gallery.removeImageByIndex(5))
				alert('There is no longer an image at position 5 to remove!');

			e.preventDefault();
		});
		
		/****************************************************************************************/

		/***************** Attach click event to the Remove Image By Hash Link ******************/
		
		$('#removeImageByHashLink').click(function(e) {
			if (!gallery.removeImageByHash('lizard'))
				alert('The lizard image has already been removed!');

			e.preventDefault();
		});
		
		/****************************************************************************************/
	});
</script>

<div id="gallery" class="content">
	<div class="slideshow-container">
		<div id="loading" class="loader"></div>
		<div id="slideshow" class="slideshow"></div>
		<div id="caption" class="caption-container"></div>
	</div>
</div>
<h1>Galer&iacute;a de fotos</h1>
<div id="thumbs" class="navigation">
	<ul class="thumbs noscript">
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/1g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/1ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/2g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/2ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/3g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/3ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/4g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/4ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/5g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/5ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/6g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/6ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/7g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/7ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/8g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/8ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/9g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/9ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/10g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/10ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/11g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/11ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/12g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/12ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/13g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/13ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/14g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/14ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/15g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/15ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/16g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/16ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/17g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/17ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
		<li>
			<a class="thumb" name="leaf" href="<?=$this->baseUrl()?>/img/galeria/19g.jpg" title="Title #0">
				<img src="<?=$this->baseUrl()?>/img/galeria/thumbnails/19ch.jpg" alt="Title #0" />
			</a>
			<div class="caption">
			</div>
		</li>
	</ul>
</div>

   