
    <div id="cont_left">
        <h1>Casas de la Playa</h1>
            <p>Con los pies sobre la arena de la playa El Desplayado, en La Pedrera, te esperamos para que disfrutes de unas vacaciones &uacute;nicas. Ubicadas en primera l&iacute;nea y frente a la zona de ba&ntilde;o con vistas de 180&deg; al mar, brindamos el confort de tu casa en la playa. Vive el sue&ntilde;o de estar a orillas del mar en un ambiente familiar y distendido con todos los servicios que necesitas para gozar de este para&iacute;so natural.</p>
        <p><b>+ Nuestra misi&oacute;n</b> es dar lo mejor de nosotros para hacer sentir a nuestros hu&eacute;spedes como en su casa. Por eso apostamos a la creatividad, buscando el m&aacute;ximo confort en equipamiento, combinando refinamiento con la rusticidad y simpleza de una casa de playa.</p>
        <p><strong>+ Nuestra visi&oacute;n</strong> est&aacute; muy comprometida con el entorno en el que vivimos y con las formas naturales, usando materiales como la madera, el bamboo y la paja que son biodegradables y se encuentran en la zona. De esta forma nos vinculamos con el ambiente, poniendo nuestro grano de arena en este m&eacute;dano que cada vez es m&aacute;s grande.</p>
        <img src="<?=$this->baseUrl()?>/img/logo/logo_small.jpg" width="81" height="27" />
	</div>
    <div id="cont_right">
    	<img src="<?=$this->baseUrl()?>/img/deco/img_casasplaya.jpg" width="589" height="529" />
   	</div>
    