<div id="cont_left">
	<h1>Servicios</h1>
	<ul>
    	<li><b>+</b> Cofre fort</li>
        <li><b>+</b> Wi-Fi</li>
        <li><b>+</b> tv cable</li>
        <li><b>+</b> servicio se mucama</li>
        <li><b>+</b> ropa blanca</li>
        <li><b>+</b> aire acondicionado</li>
        <li><b>+</b> Barbacoas (servicio de limpieza)</li>
        <li><b>+</b> Cocheras</li>
        <li><b>+</b> atenci&oacute;n las 24 hs.</li>
        <li><b>+</b> lavander&iacute;a* (opcional)</li>
        <li><b>+</b> Reposeras</li>
        <li><b>+</b> Sombras de playa</li>
	</ul>
    <img src="<?=$this->baseUrl()?>/img/logo/logo_small.jpg" width="81" height="27" />
</div>
<div id="cont_right">
	<img src="<?=$this->baseUrl()?>/img/deco/img_servicios.jpg" width="589" height="529" />
</div>