<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jquery.history.js"></script>
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAJN6AJhsXNVXnMnefgZMKBRRtFEaumzy3skH66oKx2Ihv8dgyChTSC-bJ2-wTX-Pfgdf1Vb5ep6SXhA" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">
	function initialize() { 
		//Ubication of the Casas de la Playa spot
		var latlng = new google.maps.LatLng(-34.587959, -54.122303);
		// Opciones del mapa
		var myOptions = {
		  zoom: 16,
		  center: latlng,	  
		  mapTypeId: google.maps.MapTypeId.SATELLITE,
		  streetViewControl: true
		};
		// Creo una instancia del mapa
		var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
		// Marcador del spot
	    var marker = new google.maps.Marker({
	          map: map,
	          position: new google.maps.LatLng(-34.587959, -54.122303),
	          draggable: false,
	          title: 'Casas de la Playa'
	    });
	    // Circulo overlay sobre marcador
	    var circle = new google.maps.Circle({
	    	map: map,
	    	radius: 30 // 3000 km
	    });
		// Aado el circulo al marcador
	    circle.bindTo('center', marker, 'position');
	}
</script>
<!-- We only want the thunbnails to display when javascript is disabled -->
<script type="text/javascript">
	document.write('<style>.noscript { display: none; }</style>');
	$(document).ready(function(){
		initialize();
	});
</script>
<div id="cont_left">
	<h1>Ubicaci&oacute;n</h1>
	<p>Ubicados frente a la zona de baño, en el Desplayado te esperamos para unas vacaciones únicas </p>
</div>
<div id="cont_right">
	<div id="map_canvas"></div>
</div>