<?php echo $this->doctype();?>
<html>
<head>
    <?php
    	echo $this->headMeta();
        echo $this->headTitle();
    ?>		
    <script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js"						type="text/javascript"></script>
<!-- 	<script src="<?=$this->baseUrl()?>/js/newweb_js/jMetro/js/jquery-1.6.2.min.js" 				type="text/javascript"></script>  -->
	<script src="<?=$this->baseUrl()?>/js/newweb_js/jMetro/js/jquery-ui-1.8.16.custom.min.js" 	type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/bootstrap.min.js" 							type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/jquery.carouFredSel-6.0.4-packed.js" 		type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/bjqs-1.3.min.js" 							type="text/javascript"></script>
	<link href="<?=$this->baseUrl()?>/css/newweb_css/reset.css" 				rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/js/newweb_js/jMetro/css/jquery-ui.css" 	rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap.min.css" 		rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap-responsive.css" 	rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/style.css" 				rel="stylesheet" type="text/css" />
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300' 			rel='stylesheet' type='text/css'>
	<link href="<?=$this->baseUrl()?>/images/favicon.gif" 						rel="shortcut icon"/>
	<link href="<?=$this->baseUrl()?>/images/favicon.ico" 						rel="shortcut icon"/>
	<?=$this->getAnalyticsCode();?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
	<footer>
    	<img src="<?=$this->baseUrl()?>/images/f_logo.jpg" alt="Casas de la Playa - La Pedrera" title="Casas de la Playa - La Pedrera">
    </footer>
    <a href="#" class="scrollup">Scroll</a>
</body>
</html>