<?php echo $this->doctype();?>
<html>
<head>
    <?php
    	echo $this->headMeta();
        echo $this->headTitle();
    ?>		
    <script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js"						type="text/javascript"></script>     		
	<script src="<?=$this->baseUrl()?>/js/newweb_js/ui/js/jquery-ui-1.9.2.custom.min.js" 		type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/bootstrap.min.js" 							type="text/javascript"></script>	
	<script src="<?=$this->baseUrl()?>/js/newweb_js/jquery.carouFredSel-6.0.4-packed.js" 		type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/js/newweb_js/bjqs-1.3.min.js" 							type="text/javascript"></script>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>	
	<link href="<?=$this->baseUrl()?>/css/newweb_css/reset.css" 				rel="stylesheet" type="text/css" />		
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap.min.css" 		rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/bootstrap-responsive.css" 	rel="stylesheet" type="text/css"/>
	<link href="<?=$this->baseUrl()?>/js/newweb_js/ui/css/jquery-ui.css" 		rel="stylesheet" type="text/css"/>
	<link href="<?=$this->baseUrl()?>/css/newweb_css/style.css" 				rel="stylesheet" type="text/css" />
	<link href="<?=$this->baseUrl()?>/css/newweb_css/responsive.css" 			rel="stylesheet" type="text/css" />	
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300" 			rel='stylesheet' type='text/css'>
	<link href="<?=$this->baseUrl()?>/images/favicon.gif" 						rel="shortcut icon"/>
	<link href="<?=$this->baseUrl()?>/images/favicon.ico" 						rel="shortcut icon"/>	
	<?=$this->getAnalyticsCode();?>
	<script type="text/javascript">
		function showOverlay(){
	        var overlay = $('#overlayCustom');
	        var windowHeight = $(document).height() + 'px';
	        $('#overlayCustom').css('height',windowHeight);
	        $('#overlayCustom').fadeIn("slow");
	        $('#loader').fadeIn("slow");
	    }	
	    function hideOverlay(){
	        $('#overlayCustom').fadeOut("slow");
	        $('#loader').fadeOut("slow");
	    }
	</script>
	<style type="text/css">
 		#overlayCustom{
            display: none;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 999;
            background-color: #333;
            cursor: wait;
        
            opacity:0.4;
            filter:alpha(opacity=40); /* For IE8 and earlier */
        }
        #loader{
            position: fixed;
            top: 45%;
            left: 45%;
            width: 240px;
            text-align: center;
            display: none;
            z-index: 9999;
            cursor: wait;
        }
	</style>
</head>

<body>
	<?php echo $this->layout()->content; ?>
	
	<footer>
    	<img src="<?=$this->baseUrl()?>/images/f_logo.jpg" alt="Casas de la Playa - La Pedrera" title="Casas de la Playa - La Pedrera">
    </footer>
    
    <a href="#" class="scrollup">Scroll</a>
    
    <!-- Custom Overlay -->
	<div id="overlayCustom"></div>
	<!-- Custom Progress Bar  -->
	<div id="loader">
		<img src="<?=$this->baseUrl()?>/img/ajax-loader.gif" alt="loading.." />
	</div>
</body>
</html>