<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Casa de la Playa</title>
<link href="<?=$this->baseUrl()?>/css/oldweb_css/reset.css" rel="stylesheet" type="text/css" />
<link href="<?=$this->baseUrl()?>/css/oldweb_css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/oldweb_js/jQuery/jquery-1.5.1.min.js"></script>
<link rel="shortcut icon" href="<?=$this->baseUrl()?>/img/deco/favicon.gif" />
<link rel="shortcut icon" href="<?=$this->baseUrl()?>/img/deco/favicon.ico" />
<script>
$(document).ready(function(){
	$("#" + "<?=$this->current_page?>").addClass("menu_selected");
});
</script>
</head>

<body>
	<div id="head">
	    <ul id="left">
	    	<li><a id="index" href="<?=$this->baseUrl().'/index/index'?>">Casas de la playa</a></li>
	    	<li><a id="alojamientos" href="<?=$this->baseUrl().'/index/alojamientos'?>">Alojamientos</a></li>
	    	<li><a id="ubicacion" href="<?=$this->baseUrl().'/index/ubicacion'?>">Ubicaci&oacute;n</a></li>
	    </ul>
	    <img src="<?=$this->baseUrl()?>/img/logo/logo.png" width="163" height="68" title="Casas de la playa" name="Casas de la playa"/>
	    <ul id="right">
	    	<li><a id="servicios" href="<?=$this->baseUrl().'/index/servicios'?>">Servicios</a></li>
	    	<li><a id="galeria" href="<?=$this->baseUrl().'/index/galeria'?>">Galer&iacute;a de fotos</a></li>
	    	<li><a id="lapedre" href="#">La pedrera</a></li>
	    	<li><a id="contacto" href="<?=$this->baseUrl().'/index/contacto'?>">Contacto</a></li>
	    </ul>
    </div>
    <div id="deco_sup"></div>
    <div id="cont">
    	<?php echo $this->layout()->content; ?>
    </div>
    <div id="deco_bot"></div>
    <div id="navigator">
        <ul>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/index'?>">Casas de la playa</a></li>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/alojamientos'?>">Alojamientos</a></li>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/ubicacion'?>">Ubicaci&oacute;n</a></li>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/servicios'?>">Servicios</a></li>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/galeria'?>">Galer&iacute;a de fotos</a></li>
            <li><span>+</span><a href="#">La pedrera</a></li>
            <li><span>+</span><a href="<?=$this->baseUrl().'/index/contacto'?>">Contacto</a></li>
            <li><span>+</span><a href="https://www.facebook.com/CasasDeLaPlaya">Facebook</a></li>
        </ul>
    </div>
    <div id="footer">
        <p>&reg; Casa de la Playa todos los derechos reservados.</p>
    </div>
</body>
</html>
    