<script type="text/javascript">
	$(document).ready(function() {
		// Support for AJAX loaded modal window.
		// Focuses on first input textbox after it loads the window.
		$('[data-toggle="modal"]').click(function(e) {
			e.preventDefault();
			var url = $(this).attr('href');
			if (url.indexOf('#') == 0) {
				$(url).modal('open');
			} else {
				$.get(url, function(data) { 
					$('<div class="modal hide fade span10">' + data + '</div>').modal();
				}).success(function() { $('input:text:visible:first').focus(); });
			}
		});		
		$("body").addClass("actividades");

		<?php 
			if(isset( $_GET['status'] )){
				if( $_GET['status']=='ok' && $_GET['action']=='addPost' ){
		?>
					alert('Muchas gracias por agregar su actividad, la misma sera supervisada por nuestros administradores antes de ser publicada en nuestro sitio.');
		<?php		
				}else if( $_GET['status']=='fail' ){
		?>
					alert('Algo ha salido mal, por favor intentelo nuevamente o contacte al administrador.');
		<?php		
				}			
			}	
		?>		
	});
</script>
<style type="text/css">
img {
  .img-responsive();
}
</style>

    <div class="h_int">
        <header class="container">
            <div class="row">
                <div class="span3">
                	<a href="<?=$this->baseUrl()?>/frontend/index">
                    	<img src="<?=$this->baseUrl()?>/images/h_logo.png">
                    </a>
                </div>
                <div class="span9">
                    <ul class="nav nav-pills pull-right">
                        <li><a data-toggle="modal" href="<?=$this->baseUrl()?>/frontend/quienessomos">qui&eacute;nes somos</a></li>
                        <li><a data-toggle="modal" href="<?=$this->baseUrl()?>/frontend/lapedrera">la pedrera</a></li>
                        <li><a href="<?=$this->baseUrl()?>/frontend#alojamientos">alojamientos</a></li>
                        <li><a href="<?=$this->baseUrl()?>/frontend#ubicacion">ubicaci&oacute;n</a></li>
                        <li><a href="#">actividades</a></li>
                        <li><a href="<?=$this->baseUrl()?>/frontend#contacto">contacto</a></li>
                    </ul>            
                </div>
            </div>
        </header>
    </div>
    <div class="container">
        <div class="row">
            <div class="span8">
                <h1>actividades</h1>
            </div>
            <div class="span4">
                <a class="btn pull-right" data-toggle="modal" href="<?=$this->baseUrl()?>/frontend/add-actividad"><img src="<?=$this->baseUrl()?>/images/ico/ico_more.png" width="29" height="29" />agregar actividad</a>
            </div>
        </div>
        <div class="row" style="margin-top:20px;">
        	<?php
				if($this->posts!=null){				        	 	          
		          foreach ($this->posts as $post){
	         ?> 
			            <article class="span4 act_mod" data-toggle="modal" href="<?=$this->baseUrl()?>/frontend/view-actividad?id=<?=$post['id']?>">
			            	<figure style="overflow: hidden;" >
			            		<img class="img-responsive" src="<?=$this->baseUrl()?>/uploads/big-post/<?=$this->imgs[ $post['id'] ];?>" width="256" height="184" />
			            	</figure>
			                <p><?php 
			                		$title_length = strlen ($post['title']);
			                		if( $title_length >= 55 )
			                			echo substr($post['title'], 0, 55).'...'; 
			                		else	
			                			echo $post['title'];
			                ?>
			                </p>
			            </article> 
            <?php 
		          }
				}            
            ?>           
        </div>
    </div>