<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});
</script>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1>Cargar actividad</h1>
</div>
<div class="modal-body">
    <form class="form-horizontal" style="margin-top:20px;">
    	<div class="row">
            <div class="span6 offset1">
                <div class="control-group">
                    <label class="control-label" for="inputTitle">Im&aacute;gen</label>
                    <div class="controls">
                        <input type="file" title="Search for a file to add" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputTitle">T&iacute;tulo</label>
                    <div class="controls">
                        <input type="text" id="inputTitle" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputTxt">Descripci&oacute;n</label>
                    <div class="controls">
                       <textarea id="inputTxt" class="span6"></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputName">Nombre</label>
                    <div class="controls">
                        <input type="text" id="inputName" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputLastn">Apellido</label>
                    <div class="controls">
                        <input type="text" id="inputLastn" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputEmail">E-mail</label>
                    <div class="controls">
                        <input type="text" id="inputEmail" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputPhone">Tel&eacute;fono</label>
                    <div class="controls">
                        <input type="text" id="inputPhone" class="span6">
                    </div>
                </div>
                <input type="button" value="Agregar actividad" class="btn" style="width:222px;">
            </div>
		</div>
    </form>
</div>
<div class="modal-footer">
</div>