<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});
	
	// function for contact form
	function validateData(){
		if ( $('#email').val()!='' && $('#first_name').val()!='' && $('#last_name').val()!='' && $('#description').val()!='' && $('#title').val()!='' ){
			if( confirm("Estas por de subir una actividad a nuestro sitio. La misma sera revisada por nuestros administradores antes de hacerla publica. Verifique que la imagen tenga proporciones 4x4 o 3x4 para que pueda ser visible de buena manera. Esta seguro que quiere subir esta actividad?") ) 
				return validateEmail();			
		}else{
			alert('Por favor, complete todos los campos obligatorios antes de enviar. Estos son los que tienen * a su lado');			
		}
		return false;
	}		

	// function for contact form
	function validateEmail(){
		var email = $('#email').val();
		var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;		
		if( reg.test(email) ){ 
			return true;
		}else{
			alert('Email incorrecto');
			return false;
		}			
	}	
</script>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1>Cargar actividad</h1>
</div>
<div class="modal-body modal-scroll">
    <form class="form-horizontal" style="margin-top:20px;" action="<?=$this->baseUrl()?>/frontend/create-actividad" method="post" onsubmit="return validateData();" enctype="multipart/form-data" >
    	<div class="row">
            <div class="span6 offset1">
                <div class="control-group">
                    <label class="control-label" for="image">Im&aacute;gen*</label>
                    <div class="controls">
                        <input type="file" name="image" id="image" title="Search for a file to add" class="span6" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="title">T&iacute;tulo*</label>
                    <div class="controls">
                        <input type="text" id="title" name="title" placeholder="Escriba t&iacute;tulo para su actividad..." class="span6" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="description">Descripci&oacute;n*</label>
                    <div class="controls">
                       <textarea class="span6" id="description" name="description" placeholder="Escriba descripci&oacute;n y/o ponga informaci&oacute;n para contactar su actividad como direcci&oacute;n o tel&eacute;fono..."></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="first_name">Nombre*</label>
                    <div class="controls">
                        <input type="text" id="first_name" name="first_name" placeholder="Escriba su nombre..." class="span6" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="last_name">Apellido*</label>
                    <div class="controls">
                        <input type="text" id="last_name" name="last_name" class="span6" placeholder="Escriba su apellido..." />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="email">E-mail*</label>
                    <div class="controls">
                        <input type="text" id="email" name="email" class="span6" placeholder="Escriba su email personal..." />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="telephone">Tel&eacute;fono</label>
                    <div class="controls">
                        <input type="text" id="telephone" name="telephone" class="span6" placeholder="Escriba su telefono personal..." />
                    </div>
                </div>
                <input type="submit" value="Agregar actividad" class="btn" style="width:222px;">
            </div>
		</div>
    </form>
</div>
<div class="modal-footer">
</div>