<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});
</script>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1>Cargar actividad</h1>
</div>
<div class="modal-body modal-scroll">
    <form class="form-horizontal" style="margin-top:20px;" >
    	<div class="row">
            <div class="span6 offset1">
                <div class="control-group">
                    <label class="control-label" for="image">Im&aacute;gen</label>
                    <div class="controls">
                        <input type="file" name="image" id="image" title="Search for a file to add" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="title">T&iacute;tulo</label>
                    <div class="controls">
                        <input type="text" id="title" name="title" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="description">Descripci&oacute;n</label>
                    <div class="controls">
                       <textarea class="span6" id="description" name="description"></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="first_name">Nombre</label>
                    <div class="controls">
                        <input type="text" id="first_name" name="first_name" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="last_name">Apellido</label>
                    <div class="controls">
                        <input type="text" id="last_name" name="last_name" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="email">E-mail</label>
                    <div class="controls">
                        <input type="text" id="email" name="email" class="span6">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="telephone">Tel&eacute;fono</label>
                    <div class="controls">
                        <input type="text" id="telephone" name="telephone" class="span6">
                    </div>
                </div>
                <input type="button" value="Agregar actividad" class="btn" style="width:222px;">
            </div>
		</div>
    </form>
</div>
<div class="modal-footer">
</div>