<script type="text/javascript">
	$(document).ready(function(){
		$('.btn_servicios').hover(
			function () {
				$('.serv_over').fadeIn(200);
			},
			function () {
				$('.serv_over').fadeOut(200);
			}
		);
		$('.btn_tarifas').hover(
			function () {
				$('.tarif_over').fadeIn(200);
			},
			function () {
				$('.tarif_over').fadeOut(200);
			}
		);
	});

	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});

	// when close modal we destroy the div
	$('.modal').on('shown.bs.modal', function () {
		var scrollElem2 = scrollableElement('html', 'body');
		$(scrollElem2).animate({scrollTop: 638}, 800, function() {
			location.hash = 'alojamientos';
		});	
	});
	
	// use the first element that is "scrollable"
	function scrollableElement(els) {
		for (var i = 0, argLength = arguments.length; i <argLength; i++) {
		  var el = arguments[i],
			  $scrollElement = $(el);
		  if ($scrollElement.scrollTop()> 0) {
			return el;
		  } else {
			$scrollElement.scrollTop(1);
			var isScrollable = $scrollElement.scrollTop()> 0;
			$scrollElement.scrollTop(0);
			if (isScrollable) {
			  return el;
			}
		  }
		}
		return [];
	}	
</script>

<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1>casa para 4 personas</h1>
</div>
<div class="modal-body">
    <p>Ubicadas en primera l&iacute;nea, ofrecen las mejores vistas del mar y acceso directo a la playa. Las casas cuentan con un dormitorio con balc&oacute;n, vestidor y ba&ntilde;o completo en planta alta. La cocina, el living comedor y la terraza exterior se unen en un &aacute;mbito descontracturado haciendo al espacio funcional.</p>
    <div id="myCarousel" class="carousel slide">
        <!-- Carousel items -->
        <div class="carousel-inner">
	        <div class="active item"><img src="<?=$this->baseUrl()?>/images/casas/4/001.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/002.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/003.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/004.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/005.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/006.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/007.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/008.jpg" width="750" height="444" /></div>
	        <div class="item"><img src="<?=$this->baseUrl()?>/images/casas/4/009.jpg" width="750" height="444" /></div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev"><img src="<?=$this->baseUrl()?>/images/slide/ar_left.png" width="42" height="42" /></a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next"><img src="<?=$this->baseUrl()?>/images/slide/ar_right.png" width="42" height="42" /></a>
    	<a class="btn" style="display:none">VER GALERIA</a>
    </div>
</div>
<div class="modal-footer">
	<a class="btn pull-left btn_servicios"><img src="<?=$this->baseUrl()?>/images/ico/ico_more.png" width="29" height="29" />servicios</a>
	<a class="btn pull-left btn_tarifas" ><img src="<?=$this->baseUrl()?>/images/ico/ico_tarif.png" width="29" height="29" />tarifas</a>
    <div class="serv_over">
        <ul>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> COFRE FORT</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> WI-FI</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> TV CABLE</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> limpieza diaria</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> ROPA BLANCA</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> AIRE ACONDICIONADO</li>
        </ul>
        <ul>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> BARBACOAS <span>(SERVICIO DE LIMPIEZA)</span></li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> COCHERAS</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> ATENCI&Oacute;N LAS 24 HS.</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> LAVANDER&Iacute;A* <span>(OPCIONAL)</span></li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> REPOSERAS</li>
            <li><img src="<?=$this->baseUrl()?>/images/ico/ico_check.png"> SOMBRAS DE PLAYA</li>
    	</ul>
    </div>
    <img src="<?=$this->baseUrl()?>/images/tarifas_2013.jpg" width="652" height="113" class="tarif_over"/>
    <div class="btn_mod_ico">
        <img src="<?=$this->baseUrl()?>/images/btn/btn_arrow.png" width="7" height="13" />
        <!--<input type="button" value="reservar" class="btn pull-right">-->
    </div>
</div>