<script src="<?=$this->baseUrl()?>/js/newweb_js/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});

	// when close modal we destroy the div
	$('.modal').on('shown.bs.modal', function () {
		var scrollElem2 = scrollableElement('html', 'body');
		$(scrollElem2).animate({scrollTop: 638}, 800, function() {
			location.hash = 'ubicacion';
		});	
	});
	
	// use the first element that is "scrollable"
	function scrollableElement(els) {
		for (var i = 0, argLength = arguments.length; i <argLength; i++) {
		  var el = arguments[i],
			  $scrollElement = $(el);
		  if ($scrollElement.scrollTop()> 0) {
			return el;
		  } else {
			$scrollElement.scrollTop(1);
			var isScrollable = $scrollElement.scrollTop()> 0;
			$scrollElement.scrollTop(0);
			if (isScrollable) {
			  return el;
			}
		  }
		}
		return [];
	}

	function initialize() { 
		//Ubication of the Casas de la Playa spot
		var latlng = new google.maps.LatLng(-34.587959, -54.122303);
		// Opciones del mapa
		var myOptions = {
		  zoom: 16,
		  center: latlng,	  
		  mapTypeId: google.maps.MapTypeId.SATELLITE,
		  streetViewControl: true
		};
		// Creo una instancia del mapa
		var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
		// Marcador del spot
	    var marker = new google.maps.Marker({
	          map: map,
	          position: latlng,
	          draggable: false,
	          animation: google.maps.Animation.DROP,
	          title: 'Casas de la Playa'
	    });
	    // Circulo overlay sobre marcador
	    var circle = new google.maps.Circle({
	    	map: map,
	    	radius: 30 // 3000 km
	    });
		// Aado el circulo al marcador
	    circle.bindTo('center', marker, 'position');
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="map_canvas"></div>

