<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});

	$('.modal').addClass('auto-size');
	$('.modal').addClass('auto-size-hor');	
</script>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1><?=$this->post['title'];?></h1>
</div>
<div class="modal-body modal-scroll">
	<figure class="act_img" style="overflow: hidden;">
    	<img src="<?=$this->baseUrl()?>/uploads/ampliada/<?=$this->img['name'];?>" width="484" height="397" />
    </figure>
    <p><?=$this->post['description'];?></p>
   <!--  <p><a href="<?=$this->post['web']?>" target="_blank"><?=$this->post['web']?></a></p>  --> 
     
</div>
<div class="modal-footer">
</div>