<script type="text/javascript">
	// when close modal we destroy the div
	$('.modal').on('hidden.bs.modal', function () {
		$('div.modal').remove();
	});
</script>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h1>Este t&iacute;tulo va a ser largo para ver como se comporta un t&iacute;tulo largo</h1>
</div>
<div class="modal-body">
	<figure class="act_img">
    	<img src="<?=$this->baseUrl()?>/images/uploads/test_001.jpg" width="758" height="544" />
    </figure>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere elementum lorem, vel dictum neque rhoncus sed. Quisque semper a lacus ut mollis. Cras eget odio sit amet orci sollicitudin luctus ut nec odio. Aliquam ac eros lorem. Suspendisse placerat enim quis risus rhoncus, in scelerisque mi commodo. Ut gravida sapien vitae interdum bibendum. Aenean non lobortis tellus, ac hendrerit nisl. Nullam vitae feugiat sapien.</p> 
</div>
<div class="modal-footer">
</div>